--create index idx_autorental_auto_id on ...
--create index idx_autorental_renter_id on ...
create idx_autorental_auto_id on rentals_autorental(auto_id);
create idx_autorental_renter_id on rentals_autorental(renter_id);